### ISSUE TITLE
some data file

### ISSUE THREAD

**Issue by yclzju** [wyshi/user-simulator#14]
Hi,  when I try to run sequicity_user, I can't find many files,  for example,  rest_user_simulator_goal key. json,  could you upload those files or tell me how to generate it plz,  thanks!

**Comment by wyshi** [comment]
Hello could you provide the exact name of the files?

**Comment by qbetterk** [comment]
Hi, thanks for your interest in our work.  I have just replaced the full path with the relative path in the sequicity_user and upload the related data in the directory data/multiwoz-master/data/multi-woz/.  Please try to fetch and run the code again. Also please feel free to contact us if there are more problems.
