### ISSUE TITLE
Some file missing and readme

### ISSUE THREAD

**Issue by yclzju** [wyshi/user-simulator#16]
Thanks for addressing last issue.
But I still can't run the sequicity_user when I try to train a user simulator, can you add those files or offer the code for the data preparing please? Also if you can add some details in readme about user simulator, it can help a lot, I notice that readme is for train a dialog system with sequicity, as your work and project are a little complicated, I think a readme can help a lot!
I just guess I could train a sequicity simulator by change the dataset to usr or seq_user.py, but not quite sure yet.

No such file or directory: '/data/qkun/simulator/data/multiwoz-master/db_entity_file.pkl'
  File "/home/changlin.ycl/user-simulator/simulator/user.py", line 59, in <module>
    with open("/home/wyshi/simulator/data/NNDIAL-master/db/ENTITY_POOL_no_dontcare.pkl", "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wyshi/simulator/data/NNDIAL-master/db/ENTITY_POOL_no_dontcare.pkl'
No such file or directory: '/data/qkun/simulator/data/multiwoz-master/db_entity_file.pkl'

Thanks!

**Comment by yclzju** [comment]
And I can't find this file as well: data/multiwoz-master/db/restaurant-dbase.db

I notice that your project is a little complicated, if I just only need to use your sequicity_user_simulator part, should I only need to run those codes in sequicity_user, or run_mydata_seq_new as readme?

**Comment by qbetterk** [comment]
uploaded. If you only need the sequicity_user_simulator part, then go to sequicity_user dir and run with `python model.py -mode train -model tsdf-camrest`  should work. But this would be an end-to-end dialog system for the user side.

**Comment by yclzju** [comment]
yes I still can't run successfully with python model.py -mode train -model tsdf-usr because some file missing, I will try with your uploaded version.

**Comment by qbetterk** [comment]
Sorry, I forget to merge the pr. I was quite busy this week. Please try to run it again and feel free to report any issues.
Also, I would try to fix the sequicity_user this weekend.

**Comment by yclzju** [comment]
Thanks for uploading, but I can't load that pkl file with the error"Exception has occurred: UnpicklingError invalid load key, '\x0a'."

**Comment by yclzju** [comment]
Is multi_woz_simulator911_goalkey.csv the result of your model proposed in your paper? The result of sequicity_user?

**Comment by qbetterk** [comment]
Nope, the *_goalkey.csv is formatted training data. Since the user should speak according to the given goal, we clean up the irrelated slots or other annotations and reformat the goal so that it is easier for reading.
And for the question of the file "db_entity_file.pkl", yes, it should be different. The entity file is used for delexicalization and the delexicalized entities (/special token/ slots) of user and system sides are different (of course, part of the entities are shared). So for better delexicalization, which leads to better training, we sort out the entities for user side by regex.
I hope this might answer your questions. Please point out anywhere unclear. :P

**Comment by yclzju** [comment]
> Nope, the *_goalkey.csv is formatted training data. Since the user should speak according to the given goal, we clean up the irrelated slots or other annotations and reformat the goal so that it is easier for reading.
> And for the question of the file "db_entity_file.pkl", yes, it should be different. The entity file is used for delexicalization and the delexicalized entities (/special token/ slots) of user and system sides are different (of course, part of the entities are shared). So for better delexicalization, which leads to better training, we sort out the entities for user side by regex.
> I hope this might answer your questions. Please point out anywhere unclear. :P

I think you mean *_goalkey.json is the formatted datga, multi_woz_simulator911_goalkey.csv is in results, I mean is it the user simulator result mentioned in your paper?

I know there is some difference between db_entity_file.pkl and sequicity's _replace_entity.py, but you don't give the detail of how to generate that tmp file, if I want to use a third dataset, what can I do to do this delexicalized or I just need to use _replace_entity.py (if you can give more details about delexicalizing in user-simulator, I will appreciate it).

**Comment by qbetterk** [comment]
ohhhh, I see. Yes, the *_goalkey.csv is the result. 

And for the entities, we use Regular Expression to search the entities, which cannot be directly applied to other datasets. So we did not upload related code. If you want to do that on a new dataset, you may want to skim over the whole data and write your own regex to extract slots and delexicalize sentences

**Comment by yclzju** [comment]
Also I didn't find any code about change placeholders to the slot values, did you inplement this part?

Alos, I noticed that in test phase, your simulator have db_search behvior, to my knowkedge, user simulator should not interact with db.

**Comment by qbetterk** [comment]
I am not sure why you want to change placeholders. We have already used some special tokens to separate slot values. And of course, you can disable the db_search. But this actually does not matter since the system would not offer slots at the beginning of dialogs.

**Comment by yclzju** [comment]
Em if you do want to use this simulator in practice,  you should say something like this "I want a cheap restaurant", but not " I want a price_SLOT restaurant"

**Comment by yclzju** [comment]
Thanks, in fact I find them in Seq_user.py.
